let DATA=null;
const state={module:null,index:0,order:[],cache:{},trial:null,answered:false,sound:true,mode:"auto",cue:"0",noise:"off",session:[],points:0,streak:0,voice:null,ctx:null,noiseSource:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

async function init(){DATA=await fetch("data/training-data.json").then(r=>r.json());bind();loadVoices();if("speechSynthesis"in window)speechSynthesis.onvoiceschanged=loadVoices;home();}
function bind(){
 $$(".nav,[data-screen],[data-module]").forEach(b=>b.onclick=()=>b.dataset.screen?(b.dataset.screen==="home"?home():openScreen(b.dataset.screen.split("-")[1])):open(b.dataset.module));
 $("#soundBtn").onclick=()=>{state.sound=!state.sound;$("#soundBtn").textContent=state.sound?"🔊":"🔇";if(!state.sound)stopNoise();toast(state.sound?"Sound on":"Sound muted")};
 $("#resetBtn").onclick=reset;$("#newSessionBtn").onclick=newSession;$("#repeatSessionBtn").onclick=repeatSession;$("#playBtn").onclick=play;$("#repeatBtn").onclick=play;$("#nextBtn").onclick=next;
 $("#presentationMode").onchange=e=>{state.mode=e.target.value;render()};$("#cueLevel").onchange=e=>cue(e.target.value);$("#noiseLevel").onchange=e=>{state.noise=e.target.value;if(state.noise==="off")stopNoise()};
}
function loadVoices(){if(!("speechSynthesis"in window))return;const v=speechSynthesis.getVoices();state.voice=v.find(x=>/^hi[-_]/i.test(x.lang))||v.find(x=>/hindi/i.test(x.name))||null}
function home(){state.module=null;state.index=0;state.order=[];state.cache={};show("home");stats()}
function show(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id)?.classList.add("active");$$(".nav").forEach(x=>x.classList.remove("active"));document.querySelector(`[data-screen="${id}"]`)?.classList.add("active")}
function activate(id){$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.module===String(id)||x.dataset.screen===String(id)))}
function openScreen(l){state.module="screen-"+l;state.index=0;state.order=[];state.cache={};state.trial=null;show("training");activate("screen-"+l);render()}
function open(id){state.module=String(id);state.index=0;state.order=[];state.cache={};state.trial=null;show("training");activate(id);render()}
function items(){return state.module.startsWith("screen-")?DATA.screening[state.module.split("-")[1]]:DATA.modules[state.module].items}
function list(){const a=items();if(state.order.length!==a.length){state.order=a.map((_,i)=>i);for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[state.order[i],state.order[j]]=[state.order[j],state.order[i]]}}return state.order.map(i=>a[i])}
function type(){if(state.module.startsWith("screen-")){let l=state.module.split("-")[1];return l==="A"||l==="B"?"choice":l==="C"?"completion":"open"}return DATA.modules[state.module].type}
function mode(t){return state.mode!=="auto"?state.mode:(t==="choice"||t==="sound"||t==="same-different"?"closed":"open")}
function trial(raw){let k=state.module+":"+state.index;if(state.cache[k])return state.cache[k];let b=raw.stimulus?raw:{stimulus:raw[0],options:raw,correctIndex:0};let o=b.options.map((text,i)=>({text,i}));for(let i=o.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[o[i],o[j]]=[o[j],o[i]]}return state.cache[k]={...b,options:o.map(x=>x.text),correctIndex:o.findIndex(x=>x.i===b.correctIndex)}}
function render(){if(!state.module)return;stopNoise();state.answered=false;state.trial=null;let a=list(),raw=a[state.index],t=type(),m=mode(t),letter=state.module.startsWith("screen-")?state.module.split("-")[1]:null;
 $("#moduleTag").textContent=letter?`SCREENING ${letter}`:`MODULE ${state.module}`;$("#moduleTitle").textContent=letter?({A:"Screening A — शब्द पहचान",B:"Screening B — वाक्य पहचान",C:"Screening C — sentence completion",D:"Screening D — open-set"}[letter]):DATA.modules[state.module].title;
 $("#moduleInstruction").textContent=letter?({A:"सुनें और सही शब्द पहचानें।",B:"सुनें और सही वाक्य पहचानें।",C:"पूरा prompt सुनें और completion बोलें।",D:"वाक्य सुनें और अपना response बोलें।"}[letter]):instruction(state.module);
 $("#progressText").textContent=`${state.index+1} / ${a.length}`;$("#taskCounter").textContent=`${state.index+1} / ${a.length}`;$("#progressBar").style.width=`${(state.index+1)/a.length*100}%`;$("#liveScore").textContent=state.points;$("#streakText").textContent=`🔥 ${state.streak}`;$("#presentationMode").value=state.mode;$("#cueLevel").value=state.cue;$("#noiseLevel").value=state.noise;$("#noiseControlWrap").classList.toggle("hidden-control",t!=="noise");$("#taskBadge").textContent=badge(t,m);$("#cueArea").innerHTML="";$("#feedback").textContent="";$("#feedback").className="feedback";$("#nextBtn").disabled=true;$("#playerTip").textContent="पहले stimulus सुनें";
 const area=$("#taskArea");
 if(t==="sound")return soundTask(area,raw,m);if(t==="same-different")return sameTask(area,raw);if(t==="choice")return choiceTask(area,raw,m);if(t==="completion")return completionTask(area,raw);if(t==="open-sentence")return sentenceTask(area,raw);if(t==="noise")return noiseTask(area,raw);if(t==="telephone")return phoneTask(area,raw);if(t==="conversation")return conversationTask(area,raw);if(t==="generalisation")return generalTask(area,raw);return openTask(area,raw);
}
function instruction(id){return({"1":"Environmental sound पहचानें।","2":"दो ध्वनियाँ सुनें: समान या अलग?","3":"स्वर सुनें और सही written विकल्प चुनें।","4":"Phoneme सुनें और सही written विकल्प चुनें।","5":"शब्द सुनें और सही शब्द चुनें।","6":"वाक्य सुनें और सही वाक्य चुनें।","7":"शब्द सुनें और listener से बोलने को कहें।","8":"वाक्य सुनें और प्रश्न का उत्तर बोलें।","9":"रोज़मर्रा के प्रश्न का spoken response दें।","10":"Noise के बीच target sentence सुनें।","11":"Telephone listening challenge करें।","12":"Real-life listening scenario में spoken response दें।"}[id]||"")}
function badge(t,m){return t==="sound"?"SOUND SPOTTER":t==="same-different"?"LISTEN & COMPARE":t==="choice"?(m==="closed"?"LISTEN & CHOOSE":"AUDITORY RESPONSE"):t==="noise"?"NOISE CHALLENGE":t==="telephone"?"PHONE CHALLENGE":t==="conversation"?"SPOKEN RESPONSE":t==="generalisation"?"REAL-LIFE SKILL":"LISTEN & RESPOND"}
function shell(icon,title,sub,body){return `<div class="task-content"><div class="task-icon">${icon}</div><p class="task-prompt">${title}</p><p class="task-subprompt">${sub}</p>${body}</div>`}
function scoreButtons(a="Correct",b="Incorrect"){return `<div class="score-actions"><button class="score-correct" data-score="1">✓ ${a}</button><button class="score-incorrect" data-score="0">✗ ${b}</button></div>`}
function spokenCard(title="Listener response",sub="Hindi typing आवश्यक नहीं है। Clinician score करें।"){return `<div class="spoken-card"><div class="mic">🎙️</div><h3>${title}</h3><p>${sub}</p></div>`}
function soundTask(area,raw,m){const s=[{l:"दरवाज़े की घंटी",i:"🔔",k:"doorbell"},{l:"फोन की घंटी",i:"📞",k:"phone"},{l:"प्रेशर कुकर की सीटी",i:"🍲",k:"cooker"},{l:"कार का हॉर्न",i:"🚗",k:"horn"},{l:"कुत्ते का भौंकना",i:"🐕",k:"dog"}],target=s.find(x=>raw.includes(x.l))||s[0];if(m==="open"||m==="auditory"){area.innerHTML=shell("👂","ध्वनि पहचानें","Listener बोले कि कौन-सी sound सुनी।",spokenCard("आपने क्या सुना?","Clinician response को score करें।")+scoreButtons());bindScore(target.l);return}let c=shuffle(s);area.innerHTML=shell("🔊","कौन-सी ध्वनि थी?","Stimulus सुनें और सही picture/label चुनें.",`<div class="options">${c.map(x=>`<button class="option" data-a="${x.k}"><span class="choice-icon">${x.i}</span>${esc(x.l)}</button>`).join("")}</div>`);$$(".option").forEach(b=>b.onclick=()=>choose(b,b.dataset.a===target.k,b.textContent.trim(),target.l))}
function sameTask(area,raw){area.innerHTML=shell("👂","क्या दोनों sounds समान हैं?","पहली और दूसरी ध्वनि ध्यान से सुनें.",`<div class="same-different"><div class="sound-chip">A</div><div class="versus">VS</div><div class="sound-chip">B</div></div><div class="options"><button class="option" data-a="true">✓ समान</button><button class="option" data-a="false">↔ अलग</button></div>`);$$(".option").forEach(b=>b.onclick=()=>choose(b,b.dataset.a===String(raw[2]),b.textContent.trim(),raw[2]?"समान":"अलग"))}
function choiceTask(area,raw,m){let t=trial(raw);state.trial=t;if(m==="open"||m==="auditory"){area.innerHTML=shell("🎙️","सुना हुआ response बोलें","कोई written choice नहीं है। Clinician score करें.",spokenCard()+scoreButtons());bindScore(t.stimulus);return}area.innerHTML=shell("👂","सुना हुआ विकल्प चुनें","पहले stimulus सुनें; फिर written Hindi option चुनें.",`<div class="options">${t.options.map((x,i)=>`<button class="option" data-i="${i}">${esc(x)}</button>`).join("")}</div>`);$$(".option").forEach(b=>b.onclick=()=>choose(b,+b.dataset.i===+t.correctIndex,t.options[+b.dataset.i],t.stimulus))}
function completionTask(area,r){area.innerHTML=shell("🧩","वाक्य पूरा करें","Prompt सुनें और sentence को अपने शब्दों में पूरा करें.",spokenCard("Listener बोलता है","Expected response: spoken completion.")+scoreButtons());bindScore(r.answer)}
function sentenceTask(area,r){area.innerHTML=shell("🧠","सुनें और प्रश्न का उत्तर दें","Listener उत्तर बोले; typing आवश्यक नहीं है.",spokenCard(r.question)+scoreButtons());bindScore(r.answer)}
function noiseTask(area,r){area.innerHTML=shell("🌧️","Noise के बीच target सुनें","Practice noise ऊपर से बदलें। यह calibrated clinical SNR नहीं है.",`<div class="noise-meter"><div class="bar"></div><div class="noise-label">Noise: ${state.noise}</div></div>${spokenCard("Target keyword बोलें","Listener बोले; clinician score करें.")}${scoreButtons()}`);bindScore(r.keyword)}
function phoneTask(area,r){area.innerHTML=`<div class="task-content"><div class="phone-shell"><div class="phone-screen"><div class="phone-icon">📞</div><div class="phone-status">INCOMING CALL</div><p class="task-prompt">कॉल सुनें</p><p class="task-subprompt">Transcript screen पर नहीं दिखाया गया है.</p></div></div>${scoreButtons()}</div>`;bindScore(r)}
function conversationTask(area,r){area.innerHTML=shell("💬","रोज़मर्रा का संवाद","सवाल सुनें और स्वाभाविक उत्तर दें.",spokenCard("Spoken response","Listener का response clinician score करे.")+scoreButtons("Appropriate / Correct"));bindScore(r)}
function generalTask(area,r){const icon={"दो-speaker conversation":"👥","2–4 m distance":"📏","Implanted-side listening":"👂","Competing speech":"🗣️","3-person group":"👨‍👩‍👦","Self-advocacy":"🙋"}[r]||"🌐";area.innerHTML=shell(icon,"Real-life listening challenge",`Scenario: ${esc(r)}`,spokenCard("Scenario सुनें और response दें","Functional communication के अनुसार clinician score करे.")+scoreButtons("Successful","Needs practice"));bindScore(r)}
function openTask(area,r){area.innerHTML=shell("🎤","सुनें और बोलकर जवाब दें","Listener spoken response दे; clinician score करें.",spokenCard()+scoreButtons());bindScore(typeof r==="string"?r:r.text)}
function choose(b,ok,response,target){if(state.answered)return;$$(".option").forEach(x=>x.classList.remove("correct","incorrect","selected"));b.classList.add("selected",ok?"correct":"incorrect");if(!ok)$$(".option").forEach(x=>{if(x.textContent.trim()===String(target).trim())x.classList.add("correct")});record(ok,response,target)}
function bindScore(target){$$(".score-actions button").forEach(b=>b.onclick=()=>{if(state.answered)return;$$(".score-actions button").forEach(x=>x.disabled=true);record(b.dataset.score==="1","spoken",target)})}
function record(ok,response,target){state.answered=true;state.session.push({module:state.module,index:state.index,correct:ok,response,target,presentation:mode(type())});if(ok){state.streak++;let p=10+Math.min(state.streak,5)*2;state.points+=p;feedback(`✓ सही! +${p} points`,"good")}else{state.streak=0;feedback("✗ इस item को फिर से सुनकर अभ्यास करें","bad")}$("#nextBtn").disabled=false;$("#liveScore").textContent=state.points;$("#pointsValue").textContent=state.points;$("#streakValue").textContent=state.streak;$("#streakText").textContent=`🔥 ${state.streak}`;$("#playerTip").textContent="Response recorded — अब Next दबाएँ";stats()}
function play(){if(!state.sound){toast("Sound is muted");return}let t=type(),r=list()[state.index];stopNoise();if(t==="sound"){envSound(r);return}if(t==="same-different"){speak(r[0],.78,()=>setTimeout(()=>speak(r[1],.78),650));$("#playerTip").textContent="दो sounds सुनें… फिर तुलना करें";return}let text=spoken(r,t);if(t==="noise"&&state.noise!=="off")startNoise(state.noise);speak(text,t==="telephone"?.82:.86)}
function spoken(r,t){if(state.module.startsWith("screen-")){let l=state.module.split("-")[1];if(l==="A"||l==="B")return(state.trial||trial(r)).stimulus;if(l==="C")return r.prompt;return r.text||r}if(t==="choice")return(state.trial||trial(r)).stimulus;if(t==="completion")return r.prompt;if(t==="open-sentence"||t==="noise")return r.text;if(t==="generalisation")return generalPrompt(r);return typeof r==="string"?r:r.text}
function generalPrompt(r){return({"दो-speaker conversation":"आप दो लोगों की बातचीत सुन रहे हैं। मुख्य बात सुनकर अपना जवाब दें।","2–4 m distance":"वक्ता आपसे दो से चार मीटर दूर है। बात सुनकर जवाब दें।","Implanted-side listening":"वक्ता implant वाले side पर है। बात सुनकर अपना जवाब दें।","Competing speech":"दूसरे लोग भी बोल रहे हैं। मुख्य वक्ता की बात सुनकर जवाब दें।","3-person group":"तीन लोगों के समूह में बातचीत हो रही है। अपनी बारी पर उचित जवाब दें।","Self-advocacy":"अगर आपको बात साफ नहीं सुनाई दे रही है, तो अपनी hearing need बताकर clarification माँगें।"}[r]||r)}
function speak(text,rate=.86,done){if(!state.sound||!text||!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang="hi-IN";u.rate=rate;u.pitch=1;u.volume=1;if(state.voice)u.voice=state.voice;u.onend=()=>{$("#playerTip").textContent="अब response दें";if(done)done()};u.onerror=()=>{$("#playerTip").textContent="Speech playback में समस्या हुई — फिर से सुनाएँ";if(done)done()};speechSynthesis.speak(u)}
function envSound(label){let c=audio();if(!c)return;let g=c.createGain(),now=c.currentTime;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.32,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.8);g.connect(c.destination);let k=label.includes("फोन")?"phone":label.includes("दरवाज़े")?"door":label.includes("कुकर")?"cooker":label.includes("हॉर्न")?"horn":"dog";if(k==="door")tone(c,g,740,.24);else if(k==="phone"){tone(c,g,880,.16);setTimeout(()=>tone(c,g,660,.16),210)}else if(k==="cooker")hiss(c,g,.75);else if(k==="horn")tone(c,g,180,.45);else{tone(c,g,260,.12);tone(c,g,190,.12);tone(c,g,300,.11)}$("#playerTip").textContent="Sound चल रही है… अब पहचानें"}
function tone(c,g,f,d){let o=c.createOscillator();o.type="sine";o.frequency.value=f;o.connect(g);o.start();o.stop(c.currentTime+d)}
function hiss(c,g,d){let b=c.createBuffer(1,c.sampleRate*d,c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*(1-i/x.length);let s=c.createBufferSource();s.buffer=b;s.connect(g);s.start()}
function audio(){if(!state.ctx)state.ctx=new(window.AudioContext||window.webkitAudioContext)();if(state.ctx.state==="suspended")state.ctx.resume();return state.ctx}
function startNoise(level){let c=audio();if(!c)return;stopNoise();let b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*.55;let s=c.createBufferSource(),g=c.createGain();s.buffer=b;s.loop=true;g.gain.value=level==="low"?.035:level==="medium"?.07:.12;s.connect(g).connect(c.destination);s.start();state.noiseSource=s;$(".noise-meter")?.classList.add("active")}
function stopNoise(){if(state.noiseSource){try{state.noiseSource.stop()}catch(e){}state.noiseSource=null}$(".noise-meter")?.classList.remove("active")}
function cue(v){state.cue=v;if(v==="0"){$("#cueArea").innerHTML="";return}if(v==="1"){play();$("#cueArea").innerHTML='<div class="cue-box"><strong>Repeat cue:</strong> stimulus फिर से सुनाया गया है।</div>';return}let r=list()[state.index],t=type(),target=state.trial?.stimulus||spoken(r,t);if(v==="2"){$("#cueArea").innerHTML=`<div class="cue-box"><strong>Visual cue:</strong> ${esc(String(target).trim().slice(0,1))}…</div>`;return}$("#cueArea").innerHTML=`<div class="cue-box"><strong>Clinician model:</strong> ${esc(target)}</div>`}
function next(){if(!state.answered){feedback("पहले listener response को score करें。","info");toast("Response score करना बाकी है");return}if(state.index<list().length-1){state.index++;render()}else finish()}
function finish(){let n=list().length,r=state.session.slice(-n),p=r.length?Math.round(r.filter(x=>x.correct).length/r.length*100):0;stopNoise();state.module=null;show("home");stats();$("#overallScore").textContent=`${p}%`;toast(`Module complete • ${p}% accuracy`)}
function newSession(){if(!state.module){toast("पहले कोई screening/module खोलें");return}state.index=0;state.session=[];state.points=0;state.streak=0;state.order=[];state.cache={};render();stats()}
function repeatSession(){if(!state.module){toast("पहले कोई screening/module खोलें");return}state.index=0;state.session=[];state.points=0;state.streak=0;state.trial=null;render();stats()}
function reset(){if(!confirm("पूरी session progress reset करें?"))return;stopNoise();if("speechSynthesis"in window)speechSynthesis.cancel();state.module=null;state.index=0;state.order=[];state.cache={};state.session=[];state.points=0;state.streak=0;home()}
function stats(){let n=state.session.length,c=state.session.filter(x=>x.correct).length,p=n?Math.round(c/n*100):0;$("#pointsValue").textContent=state.points;$("#streakValue").textContent=state.streak;if($("#overallScore"))$("#overallScore").textContent=n?`${p}%`:"—";if($("#completedCount"))$("#completedCount").textContent=n;if($("#homeProgressBar"))$("#homeProgressBar").style.width=`${p}%`}
function feedback(t,c){$("#feedback").textContent=t;$("#feedback").className=`feedback ${c}`}
let toastTimer;function toast(t){let e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),1800)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",init);